osx_image: xcode10
language: objective-c
sudo: required
env:
  global:
    - PROJECT="Stubber.xcodeproj"
    - SCHEME="Stubber-Package"
    - IOS_SDK="iphonesimulator12.0"
    - MACOS_SDK="macosx10.14"
    - TVOS_SDK="appletvsimulator12.0"
    - WATCHOS_SDK="watchsimulator5.0"
    - FRAMEWORK="Stubber"
  matrix:
    - SDK="$IOS_SDK"      TEST=1  DESTINATION="platform=iOS Simulator,name=iPhone XS,OS=12.0"
    - SDK="$MACOS_SDK"    TEST=1  DESTINATION="arch=x86_64"
    - SDK="$TVOS_SDK"     TEST=1  DESTINATION="OS=12.0,name=Apple TV"
    - SDK="$WATCHOS_SDK"  TEST=0  DESTINATION="OS=5.0,name=Apple Watch Series 3 - 42mm"

before_script:
  - set -o pipefail
  - make project

script:
  - if [ $TEST == 1 ]; then
      xcodebuild clean build test
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        -enableCodeCoverage YES
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    else
      xcodebuild clean build
        -project "$PROJECT"
        -scheme "$SCHEME"
        -sdk "$SDK"
        -destination "$DESTINATION"
        -configuration Debug
        CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
    fi

after_success:
  - if [ $TEST == 1 ]; then
      bash <(curl -s https://codecov.io/bash) -X xcodeplist -J 'Stubber';
    fi
