name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macOS-latest
    env:
      PROJECT: Stubber.xcodeproj
      SCHEME: Stubber-Package
      CODECOV_PACKAGE_NAME: Stubber
    strategy:
      matrix:
        env:
          - xcode: 12.2
            sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

          - xcode: 12.2
            sdk: macosx
            destination: arch=x86_64

          - xcode: 12.2
            sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV,OS=latest

          - xcode: 11.7
            sdk: iphonesimulator
            destination: platform=iOS Simulator,name=iPhone 11 Pro,OS=latest

          - xcode: 11.7
            sdk: macosx
            destination: arch=x86_64

          - xcode: 11.7
            sdk: appletvsimulator
            destination: platform=tvOS Simulator,name=Apple TV,OS=latest

    steps:
    - uses: actions/checkout@v1

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: ${{ matrix.env.xcode }}

    - name: List SDKs and Devices
      run: xcodebuild -showsdks; instruments -s

    - name: Generate Xcode Project
      run: make project

    - name: Build and Test
      run: |
        set -o pipefail && xcodebuild clean build test \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -sdk "$SDK" \
          -destination "$DESTINATION" \
          -configuration Debug \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
      env:
        SDK: ${{ matrix.env.sdk }}
        DESTINATION: ${{ matrix.env.destination }}

    - name: Upload Code Coverage
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -X xcodeplist \
          -J "$CODECOV_PACKAGE_NAME"
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
